### 1. Make a custom exception
### 2. Make a 2-d array and read and write it in a csv format

In [6]:
 
class UnderAgeError(Exception):
    pass

 
age = int(input("Enter your age: "))

try:
    if age < 18:
        raise UnderAgeError("You are not eligible to vote!")
    else:
        print("You are eligible to vote!")

except UnderAgeError as e:
    print("Caught Custom Exception:", e)



Caught Custom Exception: You are not eligible to vote!


In [8]:
import numpy as np
import csv

 
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
 
with open("my_array.csv", "w", newline="") as file:
    writer = csv.writer(file)
    writer.writerows(arr)
print("data write successfully'")

with open("my_array.csv", "r") as file:
    reader = csv.reader(file)
    loaded_array = np.array([[int(value) for value in row] for row in reader])

print("2D Array read from CSV file")
print(loaded_array)


data write successfully'
2D Array read from CSV file
[[10 20 30]
 [40 50 60]
 [70 80 90]]
