# Numpy
```
pip install numpy
```

- Mathematical Calculations
- Numpy Array Creation
- Shape
- indexing
- data types: b,i,u,f,c,m,M,O,S,u,V (https://numpy.org/doc/1.25/reference/arrays.dtypes.html#arrays-dtypes)
- more creation methods: arange, linspace, ones, zeros, eye, diag
- random numbers: Numpy Random Module
    - rand: Random values in given shape
    - randn: Return samples from the Standard normal distribution
    - randint: Return random integer from low(inclusive) to high(exclusive)
    - random: Return random floats in [0.0,1.0)
    - choice: Generates a random sample from given 1D array
    - Shuffle: Shuffle the contents of the sequence. Discuss np.random.seed()
- reshape: -1 for unknown
- slicing and assignment
- copy and view: share_memory
- operators(Element wise operations)
- and: &, or: |, not: ~ (Bitwise works same as logical in case of boolean Values)
- shape mismatch
- fancy indexing also know as filter
- search: where uses fancy indexing
- Basic reductions: sum, min, max, any, all,argmax, argmin
- Some More Numpy Functions - Statistics: mean, median, average, variance, standard deviation
- iteration: nditer, ndenumerate
- Join: concatenate, stack, hstack, vstack. Note: make a tuple of arays you want to join
- split: array_split, hsplit
- sort: np.sort
- Broadcasting
- Input from Text File
- Questions

In [1]:
import numpy as np

In [2]:
l1 = [1,2,3,4,5]
l2 = [[1,2,3],[4,5,6]]
l3 = [[[1,2,3],[4,5,6]],[[10,20,30],[40,50,60]],[[100,200,300],[400,500,600]]]

In [3]:
print(l3)

[[[1, 2, 3], [4, 5, 6]], [[10, 20, 30], [40, 50, 60]], [[100, 200, 300], [400, 500, 600]]]


In [4]:
n1 = np.array(l1)
n2 = np.array(l2)
n3 = np.array(l3)

In [7]:
print(n1,type(n1))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [8]:
n2

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
n3

array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[ 10,  20,  30],
        [ 40,  50,  60]],

       [[100, 200, 300],
        [400, 500, 600]]])

In [15]:
l3[0][1][2]

6

In [21]:
n3[0,1]

array([4, 5, 6])

In [10]:
n1.shape

(5,)

In [11]:
n2.shape

(2, 3)

In [12]:
n3.shape

(3, 2, 3)

In [11]:
n3.ndim

3

In [12]:
l3[1]

[[10, 20, 30], [40, 50, 60]]

In [22]:
n3[0,1,1]

5

In [23]:
n3[-1]

array([[100, 200, 300],
       [400, 500, 600]])

In [24]:
n3.dtype

dtype('int32')

In [31]:
# n3 = np.array(l3,dtype='float32')
# n3 = np.array(l3,dtype = 'f8')
n3 = np.array(l3,dtype = 'i8')
n3

array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[ 10,  20,  30],
        [ 40,  50,  60]],

       [[100, 200, 300],
        [400, 500, 600]]], dtype=int64)

In [46]:
print(n3[0],type(n3[0]))

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>


In [32]:
n3.dtype

dtype('int64')

In [38]:
l = [[1,2,3],[4,5]]
a = np.array(l,dtype='object')
a

array([list([1, 2, 3]), list([4, 5])], dtype=object)

In [39]:
a.shape

(2,)

In [48]:
print(a[0],type(a[0]))
a[0] = 100

[1, 2, 3] <class 'list'>


In [49]:
a

array([100, list([4, 5])], dtype=object)

more creation methods: arange, linspace, ones, zeros, eye, diag

In [55]:
n1 = np.arange(1,11,3,dtype='f4')

In [56]:
n1

array([ 1.,  4.,  7., 10.], dtype=float32)

In [59]:
np.linspace(1,3,7)

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667, 3.        ])

In [63]:
shape = [2,3,3]
np.ones(shape,dtype='i8')

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int64)

In [64]:
np.zeros((3,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [69]:
np.eye(5,6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [58]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

- random numbers: Numpy Random Module
    - rand: Random values in given shape
    - randn: Return samples from the Standard normal distribution
    - randint: Return random integer from low(inclusive) to high(exclusive)
    - random: Return random floats in [0.0,1.0)
    - choice: Generates a random sample from given 1D array
    - Shuffle: Shuffle the contents of the sequence. Discuss np.random.seed()

In [81]:
(30-10)*np.random.rand(4,5)+10

array([[11.10663199, 29.42851751, 18.56397907, 24.03350117, 25.22708545],
       [21.31501117, 21.61137181, 21.80012197, 20.9475014 , 13.66891753],
       [17.69782329, 27.5110361 , 21.57705444, 26.89452678, 29.4814536 ],
       [15.12848313, 15.70595275, 15.64374829, 28.67688778, 17.15654173]])

In [83]:
np.random.random(size = (2,3))

array([[0.05544963, 0.52634125, 0.87309074],
       [0.56164967, 0.39277698, 0.08833716]])

In [84]:
np.random.randn(3,2,3)

array([[[ 0.64157564, -0.80131988, -0.10261894],
        [-0.21391337,  0.92034914,  0.72010524]],

       [[-2.30254193, -0.1866856 , -0.5994654 ],
        [ 0.74937945,  0.38198916, -0.18761814]],

       [[ 0.58435242,  1.81024916, -2.13285901],
        [ 0.3621594 ,  0.3993919 , -0.96696301]]])

In [85]:
np.random.randint(10,20,size=(2,3))

array([[12, 15, 19],
       [10, 19, 17]])

In [74]:
np.random.choice(np.arange(10,21),size=(3,2),p = [0.5,0.1,0,0,0,0,0.2,0.2,0,0,0])

array([[17, 10],
       [10, 10],
       [16, 16]])

In [93]:
a = np.arange(10,21)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [94]:
np.random.seed(1)
np.random.shuffle(a)
a

array([12, 13, 14, 19, 11, 16, 10, 17, 20, 18, 15])

In [86]:
a = np.arange(10,22)

In [87]:
a.shape

(12,)

In [88]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [95]:
b = a.reshape((2,-1,2))

In [96]:
b

array([[[10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21]]])

In [98]:
b.reshape(-1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [99]:
a = np.arange(100).reshape((10,10))

In [100]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [103]:
a[2:7,3:7]

array([[23, 24, 25, 26],
       [33, 34, 35, 36],
       [43, 44, 45, 46],
       [53, 54, 55, 56],
       [63, 64, 65, 66]])

In [105]:
a[5:8,::-1]

array([[59, 58, 57, 56, 55, 54, 53, 52, 51, 50],
       [69, 68, 67, 66, 65, 64, 63, 62, 61, 60],
       [79, 78, 77, 76, 75, 74, 73, 72, 71, 70]])

In [106]:
b = a[3:7]

In [107]:
b

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [108]:
b[0] = np.arange(1000,1010)

In [109]:
b

array([[1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009],
       [  40,   41,   42,   43,   44,   45,   46,   47,   48,   49],
       [  50,   51,   52,   53,   54,   55,   56,   57,   58,   59],
       [  60,   61,   62,   63,   64,   65,   66,   67,   68,   69]])

In [110]:
a

array([[   0,    1,    2,    3,    4,    5,    6,    7,    8,    9],
       [  10,   11,   12,   13,   14,   15,   16,   17,   18,   19],
       [  20,   21,   22,   23,   24,   25,   26,   27,   28,   29],
       [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009],
       [  40,   41,   42,   43,   44,   45,   46,   47,   48,   49],
       [  50,   51,   52,   53,   54,   55,   56,   57,   58,   59],
       [  60,   61,   62,   63,   64,   65,   66,   67,   68,   69],
       [  70,   71,   72,   73,   74,   75,   76,   77,   78,   79],
       [  80,   81,   82,   83,   84,   85,   86,   87,   88,   89],
       [  90,   91,   92,   93,   94,   95,   96,   97,   98,   99]])

In [111]:
np.shares_memory(a,b)

True

In [112]:
c = a[3:7].copy()

In [113]:
c[0] = np.arange(100,110)

In [114]:
c

array([[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69]])

In [115]:
a

array([[   0,    1,    2,    3,    4,    5,    6,    7,    8,    9],
       [  10,   11,   12,   13,   14,   15,   16,   17,   18,   19],
       [  20,   21,   22,   23,   24,   25,   26,   27,   28,   29],
       [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009],
       [  40,   41,   42,   43,   44,   45,   46,   47,   48,   49],
       [  50,   51,   52,   53,   54,   55,   56,   57,   58,   59],
       [  60,   61,   62,   63,   64,   65,   66,   67,   68,   69],
       [  70,   71,   72,   73,   74,   75,   76,   77,   78,   79],
       [  80,   81,   82,   83,   84,   85,   86,   87,   88,   89],
       [  90,   91,   92,   93,   94,   95,   96,   97,   98,   99]])

In [137]:
np.shares_memory(a,c)

False

In [144]:
a[3:6,2:4] = np.arange(200,206).reshape((3,2))

In [142]:
a

array([[   0,    1,    2,    3,    4,    5,    6,    7,    8,    9],
       [  10,   11,   12,   13,   14,   15,   16,   17,   18,   19],
       [  20,   21,   22,   23,   24,   25,   26,   27,   28,   29],
       [1000, 1001,  200,  201, 1004, 1005, 1006, 1007, 1008, 1009],
       [  40,   41,  202,  203,   44,   45,   46,   47,   48,   49],
       [  50,   51,  204,  205,   54,   55,   56,   57,   58,   59],
       [  60,   61,   62,   63,   64,   65,   66,   67,   68,   69],
       [  70,   71,   72,   73,   74,   75,   76,   77,   78,   79],
       [  80,   81,   82,   83,   84,   85,   86,   87,   88,   89],
       [  90,   91,   92,   93,   94,   95,   96,   97,   98,   99]])

- operators(Element wise operations)
- and: &, or: |, not: ~
- shape mismatch
- fancy indexing also know as filter
- search: where uses fancy indexing
- Basic reductions: sum, min, max, any, all,argmax, argmin
- Some More Numpy Functions - Statistics: mean, median, average, variance, standard deviation
- iteration: nditer, ndenumerate
- Join: concatenate, stack, hstack, vstack. Note: make a tuple of arays you want to join
- split: array_split, hsplit
- sort: np.sort
- Broadcasting
- Input from Text File
- Questions

In [17]:
import numpy as np
a = np.arange(11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
a + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [5]:
a - 5

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5])

In [6]:
a*5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [7]:
a/5

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [8]:
a // 5

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2], dtype=int32)

In [9]:
a % 5

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0], dtype=int32)

In [10]:
a ** 5

array([     0,      1,     32,    243,   1024,   3125,   7776,  16807,
        32768,  59049, 100000], dtype=int32)

In [13]:
b = np.array([3,2,7,6,1,7,4,8,3])
b >= 5

array([False, False,  True,  True, False,  True, False,  True, False])

In [14]:
a += 5

In [15]:
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [30]:
a = np.arange(10)
b = np.arange(10,20)
c = np.arange(20,40)
c

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39])

In [22]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [31]:
a + c

ValueError: operands could not be broadcast together with shapes (10,) (20,) 

In [27]:
a/b

array([0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429,
       0.33333333, 0.375     , 0.41176471, 0.44444444, 0.47368421])

In [29]:
a <= b

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [38]:
a = np.arange(0,10).reshape((5,2))
b = np.arange(0,10).reshape((5,2))

In [39]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [40]:
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [35]:
a+b

array([[20, 22],
       [24, 26],
       [28, 30],
       [32, 34],
       [36, 38]])

In [41]:
np.logical_and(a,b)

array([[False,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

In [44]:
(a >= b) | (b > 5)

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

In [183]:
np.add(a,b)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [184]:
np.subtract(a,b)

array([-10, -10, -10, -10, -10, -10, -10, -10, -10, -10])

In [185]:
np.multiply(a,b)

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

In [186]:
np.divide(a,b)

array([0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429,
       0.33333333, 0.375     , 0.41176471, 0.44444444, 0.47368421])

In [187]:
np.divmod(a,b)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [45]:
x = np.array([1,2,3,4,5,6,7])
m = 2
c = 3
y = m*x+c
print(y)

[ 5  7  9 11 13 15 17]


In [56]:
a = np.arange(10,20)
b = np.arange(10,21)

In [57]:
a+b

ValueError: operands could not be broadcast together with shapes (10,) (11,) 

In [58]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [59]:
a[[0,3,9,9]]

array([10, 13, 19, 19])

In [105]:
a = np.arange(100).reshape((10,10))

In [61]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [62]:
a[[6,3,8,2]]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [72]:
a[[6,5,2,8],[0,2,4,6]]

array([60, 52, 24, 86])

In [64]:
a[[9,2,0,6],[9,2,0,6]]

array([99, 22,  0, 66])

In [67]:
a[:,[5,3,8,7]]

array([[ 5,  3,  8,  7],
       [15, 13, 18, 17],
       [25, 23, 28, 27],
       [35, 33, 38, 37],
       [45, 43, 48, 47],
       [55, 53, 58, 57],
       [65, 63, 68, 67],
       [75, 73, 78, 77],
       [85, 83, 88, 87],
       [95, 93, 98, 97]])

In [71]:
a[[6,3,8,2]][:,[2,4,7,9]]

array([[62, 64, 67, 69],
       [32, 34, 37, 39],
       [82, 84, 87, 89],
       [22, 24, 27, 29]])

In [102]:
a = np.array([10,23,31,40,50])

In [103]:
a

array([10, 23, 31, 40, 50])

In [104]:
a[[True,False,True,True,False]]

array([10, 31, 40])

In [106]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [107]:
a[[True,False,True,False,True,False,False,True,True,False]]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [84]:
a[:,[True,False,True,False,False,True,False,True,False,False]]

array([[ 0,  2,  5,  7],
       [10, 12, 15, 17],
       [20, 22, 25, 27],
       [30, 32, 35, 37],
       [40, 42, 45, 47],
       [50, 52, 55, 57],
       [60, 62, 65, 67],
       [70, 72, 75, 77],
       [80, 82, 85, 87],
       [90, 92, 95, 97]])

In [109]:
a[a%3 == 0]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [86]:
a[a%5 == 0]

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [90]:
a[a[:,0]%4 == 0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [228]:
a[:,a[0]%4 == 0]

array([[ 0,  4,  8],
       [10, 14, 18],
       [20, 24, 28],
       [30, 34, 38],
       [40, 44, 48],
       [50, 54, 58],
       [60, 64, 68],
       [70, 74, 78],
       [80, 84, 88],
       [90, 94, 98]])

In [117]:
a = np.arange(60).reshape((12,5))

In [118]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [128]:
#axis = 0 means mean of column
#axis = 1 means mean of row
np.mean(a,axis = 1)

array([ 2.,  7., 12., 17., 22., 27., 32., 37., 42., 47., 52., 57.])

In [125]:
np.sum(a,axis = 1)

array([ 10,  35,  60,  85, 110, 135, 160, 185, 210, 235, 260, 285])

In [121]:
np.max(a)

59

In [131]:
a = np.array([1,2,3])
b = np.array([[10,20,30],[40,50,60],[70,80,90]])

In [132]:
a+b

array([[11, 22, 33],
       [41, 52, 63],
       [71, 82, 93]])

In [133]:
a = np.array([[1],[2],[3]])
b = np.array([[10,20,30],[40,50,60],[70,80,90]])

In [134]:
a

array([[1],
       [2],
       [3]])

In [135]:
b

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [136]:
a+b

array([[11, 21, 31],
       [42, 52, 62],
       [73, 83, 93]])

In [153]:
a = np.array([0,1,2,3,4])
b = np.array([[4],[5],[6],[7]])

In [154]:
a

array([0, 1, 2, 3, 4])

In [155]:
b

array([[4],
       [5],
       [6],
       [7]])

In [156]:
a

array([0, 1, 2, 3, 4])

In [157]:
b

array([[4],
       [5],
       [6],
       [7]])

In [158]:
a+b

array([[ 4,  5,  6,  7,  8],
       [ 5,  6,  7,  8,  9],
       [ 6,  7,  8,  9, 10],
       [ 7,  8,  9, 10, 11]])

In [165]:
a = np.array([10,3,20,4,1])

In [167]:
np.argmax(a)

2

In [168]:
data = np.loadtxt('E:/DS Classes/GLA_GenAI2025/Numpy and Pandas/populations.txt')
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [170]:
np.max(data,axis = 0)

array([ 1920., 77400., 59400., 48300.])

In [172]:
np.argmax(data,axis = 1)

array([3, 3, 1, 1, 2, 2, 3, 3, 3, 3, 3, 3, 1, 1, 1, 2, 3, 3, 3, 3, 3],
      dtype=int64)

In [294]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [295]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [296]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [297]:
a@b

array([[19, 22],
       [43, 50]])

In [299]:
a = np.array([1,2,3])
b = np.array([7,8,9])
a@b

np.int64(50)