# Pandas 
```
pip install pandas 
pip install --upgrade pandas
```
- Pandas Series
- Pandas DataFrame --> use various ways to initialize it(dtype,columns,index)
- shape
- head
- tail
- convert to numpy array --> values
- columns
- to_csv (index = false)
- read_csv
-  drop(columns=[])
-  describe()
-  info()
-  iloc
-  loc
-  Access Particular Columns
-  indexing and slicing --> multirow and col
-  columns.get_loc
-  Fancy indexing
-  Filtering
-  unique
-  sort_values(by,ascending)
-  getdummies 
- groupby --> column name, various functions on grp, iterate
- pivot --> summarize and aggregate data,Grouper
- concat--> give as list, ignore_index,join
- merge--> on,how
- dropna
- fillna
- interpolate
- pip install matplotlib

In [14]:
import pandas as pd
import numpy as np

In [15]:
print(pd.__version__)
pd.DF = pd.DataFrame

2.2.3


In [16]:
l1 = [10,20,30,40,50]

In [23]:
pds = pd.Series(l1,index = ['A','B','C','D','E'],dtype='f4')

In [24]:
pds

A    10.0
B    20.0
C    30.0
D    40.0
E    50.0
dtype: float32

In [25]:
type(pds)

pandas.core.series.Series

In [27]:
pds['B']

20.0

In [28]:
marks = {
    'Phy': [92,71,60,95,99],
    'Chem': [75,93,99,58,80],
    'Maths': [95,99,93,86,89]
}

In [29]:
marks

{'Phy': [92, 71, 60, 95, 99],
 'Chem': [75, 93, 99, 58, 80],
 'Maths': [95, 99, 93, 86, 89]}

In [32]:
df = pd.DataFrame(marks,index=['A','B','C','D','E'])

In [33]:
df

Phy  Chem  Maths
A   92    75     95
B   71    93     99
C   60    99     93
D   95    58     86
E   99    80     89

In [35]:
na = np.random.randint(0,100,(10,3))
na

array([[19, 76, 72],
       [45, 50, 39],
       [73, 69, 39],
       [26, 78, 39],
       [40, 43, 43],
       [56, 92, 13],
       [12, 74, 57],
       [78, 42, 83],
       [90,  7, 70],
       [91, 91, 50]])

In [39]:
df2 = pd.DataFrame(na,columns=['Phy','Chem','Maths'])

In [40]:
df2

Phy  Chem  Maths
0   19    76     72
1   45    50     39
2   73    69     39
3   26    78     39
4   40    43     43
5   56    92     13
6   12    74     57
7   78    42     83
8   90     7     70
9   91    91     50

In [43]:
df

Phy  Chem  Maths
A   92    75     95
B   71    93     99
C   60    99     93
D   95    58     86
E   99    80     89

In [44]:
df.shape

(5, 3)

In [47]:
df2.head(2)

Phy  Chem  Maths
0   19    76     72
1   45    50     39

In [48]:
df2.tail(3)

Phy  Chem  Maths
7   78    42     83
8   90     7     70
9   91    91     50

In [49]:
df.values

array([[92, 75, 95],
       [71, 93, 99],
       [60, 99, 93],
       [95, 58, 86],
       [99, 80, 89]], dtype=int64)

In [50]:
df.columns

Index(['Phy', 'Chem', 'Maths'], dtype='object')

In [52]:
df2.columns

Index(['Phy', 'Chem', 'Maths'], dtype='object')

In [62]:
df

Phy  Chem  Maths
A   74    41     65
B   70     9      9
C   63    37     38
D   98    56     56
E   72    48     34

In [53]:
df.to_csv("Marks.csv")

In [56]:
ndf = pd.read_csv("Marks.csv",index_col='Unnamed: 0')

In [57]:
ndf

Phy  Chem  Maths
A   92    75     95
B   71    93     99
C   60    99     93
D   95    58     86
E   99    80     89

In [69]:
df.to_csv("Marks.csv",sep='|',index = False)

In [70]:
ndf = pd.read_csv("Marks.csv",sep='|')
ndf

Phy  Chem  Maths
0   92    75     95
1   71    93     99
2   60    99     93
3   95    58     86
4   99    80     89

In [71]:
ndf.index = ['A','B','C','D','E']

In [72]:
ndf

Phy  Chem  Maths
A   92    75     95
B   71    93     99
C   60    99     93
D   95    58     86
E   99    80     89

In [73]:
df

Phy  Chem  Maths
A   92    75     95
B   71    93     99
C   60    99     93
D   95    58     86
E   99    80     89

In [76]:
df.drop(columns=['Chem'])

Phy  Maths
A   92     95
B   71     99
C   60     93
D   95     86
E   99     89

In [77]:
df

Phy  Chem  Maths
A   92    75     95
B   71    93     99
C   60    99     93
D   95    58     86
E   99    80     89

In [78]:
df2

Phy  Chem  Maths
0   19    76     72
1   45    50     39
2   73    69     39
3   26    78     39
4   40    43     43
5   56    92     13
6   12    74     57
7   78    42     83
8   90     7     70
9   91    91     50

In [79]:
df2.describe()

Phy      Chem      Maths
count  10.000000  10.00000  10.000000
mean   53.000000  62.20000  50.500000
std    29.147136  26.49025  20.549398
min    12.000000   7.00000  13.000000
25%    29.500000  44.75000  39.000000
50%    50.500000  71.50000  46.500000
75%    76.750000  77.50000  66.750000
max    91.000000  92.00000  83.000000

In [80]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Phy     10 non-null     int32
 1   Chem    10 non-null     int32
 2   Maths   10 non-null     int32
dtypes: int32(3)
memory usage: 252.0 bytes


In [83]:
df[['Phy','Maths']]

Phy  Maths
A   92     95
B   71     99
C   60     93
D   95     86
E   99     89

In [87]:
df.iloc[0:3,:]

Phy  Chem  Maths
A   92    75     95
B   71    93     99
C   60    99     93

In [89]:
df.iloc[2,2]

93

In [91]:
df.loc[['A','C'],['Phy','Maths']]

Phy  Maths
A   92     95
C   60     93

In [93]:
df.iloc[[True,False,False,True,True]]

Phy  Chem  Maths
A   92    75     95
D   95    58     86
E   99    80     89

In [96]:
df[df['Phy'] >= 73]

Phy  Chem  Maths
A   92    75     95
D   95    58     86
E   99    80     89

In [113]:
ndf1 = df[df['Phy'] >= 80]
ndf1[ndf1['Chem'] >= 80]

Phy  Chem  Maths
E   99    80     89

In [112]:
df.columns.get_loc('Maths')

2

In [115]:
df2['Phy'].unique()

array([19, 45, 73, 26, 40, 56, 12, 78, 90, 91])

In [117]:
a = np.array([1,3,1,2,4,1,3,2,4,1,2,3,1,4])

In [119]:
np.unique(a,return_counts=True)

(array([1, 2, 3, 4]), array([5, 3, 3, 3], dtype=int64))

In [120]:
df

Phy  Chem  Maths
A   74    41     65
B   70     9      9
D   98    56     56
E   72    48     34

In [120]:
df.sort_values(by = 'Phy',axis = 0,ascending=False)

Phy  Chem  Maths
E   99    80     89
D   95    58     86
A   92    75     95
B   71    93     99
C   60    99     93

In [121]:
df.sort_values(by = 'A',axis = 1,ascending=False)

Maths  Phy  Chem
A     95   92    75
B     99   71    93
C     93   60    99
D     86   95    58
E     89   99    80

In [124]:
pds = pd.Series(['A','B','C','B','A','B'])

In [125]:
pds

0    A
1    B
2    C
3    B
4    A
5    B
dtype: object

In [128]:
pdd = pd.get_dummies(pds,dtype='i1')

In [129]:
pdd

A  B  C
0  1  0  0
1  0  1  0
2  0  0  1
3  0  1  0
4  1  0  0
5  0  1  0

In [131]:
data = pd.read_csv("weather_data_cities.csv")

In [132]:
data

day      city  temperature  windspeed   event
0   1/1/2017  new york           32          6    Rain
1   1/2/2017  new york           36          7   Sunny
2   1/3/2017  new york           28         12    Snow
3   1/4/2017  new york           33          7   Sunny
4   1/1/2017    mumbai           90          5   Sunny
5   1/2/2017    mumbai           85         12     Fog
6   1/3/2017    mumbai           87         15     Fog
7   1/4/2017    mumbai           92          5    Rain
8   1/1/2017     paris           45         20   Sunny
9   1/2/2017     paris           50         13  Cloudy
10  1/3/2017     paris           54          8  Cloudy
11  1/4/2017     paris           42         10  Cloudy

In [135]:
data[data['city'] == 'new york']['temperature'].mean()

32.25

In [136]:
gdf = data.groupby(by = 'city')

In [137]:
for city,group in gdf:
    print(city)
    print(group)
    print()

mumbai
        day    city  temperature  windspeed  event
4  1/1/2017  mumbai           90          5  Sunny
5  1/2/2017  mumbai           85         12    Fog
6  1/3/2017  mumbai           87         15    Fog
7  1/4/2017  mumbai           92          5   Rain

new york
        day      city  temperature  windspeed  event
0  1/1/2017  new york           32          6   Rain
1  1/2/2017  new york           36          7  Sunny
2  1/3/2017  new york           28         12   Snow
3  1/4/2017  new york           33          7  Sunny

paris
         day   city  temperature  windspeed   event
8   1/1/2017  paris           45         20   Sunny
9   1/2/2017  paris           50         13  Cloudy
10  1/3/2017  paris           54          8  Cloudy
11  1/4/2017  paris           42         10  Cloudy



In [138]:
gdf['temperature'].mean()

city
mumbai      88.50
new york    32.25
paris       47.75
Name: temperature, dtype: float64

In [141]:
gdf = data.groupby(by = 'event')
gdf['temperature'].mean()

event
Cloudy    48.666667
Fog       86.000000
Rain      62.000000
Snow      28.000000
Sunny     51.000000
Name: temperature, dtype: float64

In [165]:
data

day      city  temperature  windspeed   event
0   1/1/2017  new york           32          6    Rain
1   1/2/2017  new york           36          7   Sunny
2   1/3/2017  new york           28         12    Snow
3   1/4/2017  new york           33          7   Sunny
4   1/1/2017    mumbai           90          5   Sunny
5   1/2/2017    mumbai           85         12     Fog
6   1/3/2017    mumbai           87         15     Fog
7   1/4/2017    mumbai           92          5    Rain
8   1/1/2017     paris           45         20   Sunny
9   1/2/2017     paris           50         13  Cloudy
10  1/3/2017     paris           54          8  Cloudy
11  1/4/2017     paris           42         10  Cloudy

In [166]:
data.pivot(columns='city',index='day')

temperature                windspeed                 event           \
city          mumbai new york paris    mumbai new york paris mumbai new york   
day                                                                            
1/1/2017          90       32    45         5        6    20  Sunny     Rain   
1/2/2017          85       36    50        12        7    13    Fog    Sunny   
1/3/2017          87       28    54        15       12     8    Fog     Snow   
1/4/2017          92       33    42         5        7    10   Rain    Sunny   

                  
city       paris  
day               
1/1/2017   Sunny  
1/2/2017  Cloudy  
1/3/2017  Cloudy  
1/4/2017  Cloudy

In [179]:
d1 = {
    'A' : [10,20,30,40],
    'B' : [3,4,5,6]
}
d2 = {
    'A' : [30,40,50,60],
    'C' : [3,4,5,6]
}

In [180]:
df1 = pd.DataFrame(d1)
df2 = pd.DataFrame(d2)

In [181]:
df1

A  B
0  10  3
1  20  4
2  30  5
3  40  6

In [182]:
df2

A  C
0  30  3
1  40  4
2  50  5
3  60  6

In [187]:
df3 = pd.concat([df1,df2],join='inner',ignore_index=True)
df3

A
0  10
1  20
2  30
3  40
4  30
5  40
6  50
7  60

In [193]:
mdf3 = pd.merge(df1,df2,how='outer')
mdf3

A    B    C
0  10  3.0  NaN
1  20  4.0  NaN
2  30  5.0  3.0
3  40  6.0  4.0
4  50  NaN  5.0
5  60  NaN  6.0

In [194]:
mdf3.dropna()

A    B    C
2  30  5.0  3.0
3  40  6.0  4.0

In [199]:
mdf3.fillna(mdf3.mean())

A    B    C
0  10  3.0  4.5
1  20  4.0  4.5
2  30  5.0  3.0
3  40  6.0  4.0
4  50  4.5  5.0
5  60  4.5  6.0

In [198]:
mdf3.mean()

A    35.0
B     4.5
C     4.5
dtype: float64

In [209]:
mdf3.interpolate('linear',limit_direction='both')

A    B    C
0  10  3.0  3.0
1  20  4.0  3.0
2  30  5.0  3.0
3  40  6.0  4.0
4  50  6.0  5.0
5  60  6.0  6.0