In [104]:
import numpy as np
import pandas as pd

### Task 1: Creating Arrays 
1. Write a Python program to:  
- Create a 1D NumPy array of 10 integers ranging from 1 to 10. 
- Create a 2D NumPy array of shape (3, 3) with integers from 1 
to 9. 
- Create a 3D NumPy array with random floating-point numbers 
of shape (3, 5, 3). 
2. Display the shape, size, and datatype of each array. 

In [105]:
OneDArray = np.arange(1,11)
print(OneDArray, type(OneDArray), OneDArray.shape, OneDArray.size, OneDArray.dtype)
print("-"*40)


TwoDArray = np.random.randint(1, 10, size=(3,3))
print(TwoDArray, type(TwoDArray), TwoDArray.shape, TwoDArray.size, TwoDArray.dtype)
print("-"*40)


ThreeDArray = np.random.rand( 3,5,3)
print(ThreeDArray, type(ThreeDArray), ThreeDArray.shape, ThreeDArray.size, ThreeDArray.dtype)



[ 1  2  3  4  5  6  7  8  9 10] <class 'numpy.ndarray'> (10,) 10 int64
----------------------------------------
[[3 4 8]
 [9 4 2]
 [2 4 4]] <class 'numpy.ndarray'> (3, 3) 9 int32
----------------------------------------
[[[0.70544489 0.57142012 0.99076342]
  [0.54845819 0.51443333 0.13364396]
  [0.49179851 0.97777192 0.137732  ]
  [0.58900635 0.30952095 0.51105733]
  [0.52379239 0.29099289 0.90489083]]

 [[0.72486045 0.66457282 0.21754367]
  [0.64687034 0.65323282 0.11676417]
  [0.91513011 0.64326483 0.23788801]
  [0.364762   0.53232159 0.0189964 ]
  [0.05276096 0.27790883 0.26311144]]

 [[0.75659055 0.38436497 0.23274283]
  [0.86967964 0.96345034 0.49085259]
  [0.37785472 0.33271544 0.63277756]
  [0.58789492 0.21285817 0.85152663]
  [0.43630445 0.30717883 0.45206896]]] <class 'numpy.ndarray'> (3, 5, 3) 45 float64


In [106]:
 
OneDArray = np.arange(1, 11)
print(" 1D Array:")
print(OneDArray)
print("Type:", type(OneDArray))
print("Shape:", OneDArray.shape)
print("Size:", OneDArray.size)
print("Data Type:", OneDArray.dtype)
print("-" * 40)

 
TwoDArray = np.random.randint(1, 10, size=(3, 3))
print(" 2D Array:")
print(TwoDArray)
print("Type:", type(TwoDArray))
print("Shape:", TwoDArray.shape)
print("Size:", TwoDArray.size)
print("Data Type:", TwoDArray.dtype)
print("-" * 40)

 
ThreeDArray = np.random.rand(3, 5, 3)
print(" 3D Array:")
print(ThreeDArray)
print("Type:", type(ThreeDArray))
print("Shape:", ThreeDArray.shape)
print("Size:", ThreeDArray.size)
print("Data Type:", ThreeDArray.dtype)
print("-" * 40)


 1D Array:
[ 1  2  3  4  5  6  7  8  9 10]
Type: <class 'numpy.ndarray'>
Shape: (10,)
Size: 10
Data Type: int64
----------------------------------------
 2D Array:
[[7 2 4]
 [5 9 4]
 [3 1 1]]
Type: <class 'numpy.ndarray'>
Shape: (3, 3)
Size: 9
Data Type: int32
----------------------------------------
 3D Array:
[[[0.48646134 0.74922292 0.60448597]
  [0.32968729 0.77446784 0.54120304]
  [0.9977695  0.32694246 0.65775145]
  [0.14505748 0.92863072 0.5042328 ]
  [0.22443672 0.12816139 0.92183562]]

 [[0.77473312 0.83768081 0.8742527 ]
  [0.0676991  0.19963229 0.24486895]
  [0.50329158 0.85209299 0.51692513]
  [0.82008447 0.38715348 0.16303647]
  [0.85453469 0.13671891 0.44435676]]

 [[0.48637996 0.37328489 0.26602539]
  [0.49311336 0.39428041 0.89626836]
  [0.69914756 0.31047192 0.17986245]
  [0.30191249 0.25150917 0.25807872]
  [0.36585097 0.56003376 0.62196335]]]
Type: <class 'numpy.ndarray'>
Shape: (3, 5, 3)
Size: 45
Data Type: float64
----------------------------------------


### Task 2: Array Indexing and Slicing 
1. Create a NumPy array from the following list:  
data = [10, 20, 30, 40, 50, 60, 70, 80, 90] 
2. Write a Python program to:  
- Retrieve the first three elements of the array. 
- Retrieve every alternate element of the array. 
- Reverse the array. 
3. Perform the above operations and display the results.

In [107]:
data = [10, 20, 30, 40, 50, 60, 70, 80, 90] 
n1 = np.array(data)
print(n1, type(n1))

firstThreeEle = n1[:3]
print(firstThreeEle)

AlternateEle = n1[::2]
print(AlternateEle)

ReverseEle = n1[::-1]
print(ReverseEle) 


[10 20 30 40 50 60 70 80 90] <class 'numpy.ndarray'>
[10 20 30]
[10 30 50 70 90]
[90 80 70 60 50 40 30 20 10]


### Task 3: Mathematical Operations 
1. Create two NumPy arrays, A and B, each with 5 random integers 
between 1 and 20. 
2. Write a Python program to:  
- Add, subtract, multiply, and divide the two arrays element
wise. 
- Compute the dot product of the arrays. 
- Find the mean, median, standard deviation, and variance of 
array A. 
- Identify the maximum and minimum values in array B and 
their indices.

In [108]:
A = np.random.randint(1, 20, size=(5))
B = np.random.randint(1, 20, size=(5))

Add = A + B
print('Addition : ',Add)

subtract = A - B
print('Subtraction : ',subtract)

mul = A * B
print('Multiplication : ',mul)

divide = A / B
print('Division : ',divide)



dotPro = np.dot(A, B)
print('Dot product : ', dotPro)

mean = A.mean()
print('Mean : ',mean)

median = np.median(A)
print('median : ',median)

stdDev = np.std(A)
print(f"Standard Deviation: {stdDev:.2f}")


variance = stdDev ** 2
print(f"Variance : {variance:.2f}")


min = np.min(B)
minIdx = np.argmin(B)
print("Min Element : ", min)
print("Min Element index: ", minIdx)


max = np.max(B)
maxIdx = np.argmax(B)
print("Max Element : ", max)
print("Max Element index: ", maxIdx)




Addition :  [24 28 19 20 29]
Subtraction :  [-12   8  -1   2  -1]
Multiplication :  [108 180  90  99 210]
Division :  [0.33333333 1.8        0.9        1.22222222 0.93333333]
Dot product :  687
Mean :  11.6
median :  11.0
Standard Deviation: 4.13
Variance : 17.04
Min Element :  9
Min Element index:  3
Max Element :  18
Max Element index:  0


### Task 4: Reshaping and Transposing 
1. Create a 1D NumPy array of 12 integers ranging from 1 to 12. 
2. Write a Python program to:  
- Reshape the array into a 2D array of shape (4, 3). 
- Reshape the array into a 3D array of shape (2, 2, 3). 
- Transpose the reshaped 2D array and display its shape.

In [109]:
n1 = np.arange(1, 13)
print(n1, type(n1))


print("Reshape (4 x 3) : ")
print(n1.reshape(4,3))


print("-"*40)
print("Reshape (2 x 2 x 3) : ")
print( n1.reshape(2,2,3))

print("-"*40)


print("Transpose Matrix : ")
TwoD = n1.reshape(4,3)

transpose2D = TwoD.transpose()
print(transpose2D)


[ 1  2  3  4  5  6  7  8  9 10 11 12] <class 'numpy.ndarray'>
Reshape (4 x 3) : 
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
----------------------------------------
Reshape (2 x 2 x 3) : 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
----------------------------------------
Transpose Matrix : 
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


### Task 5: Boolean Masking and Filtering 
1. Create a NumPy array with 15 random integers between 10 and 50. 
2. Write a Python program to:  
- Find all elements greater than 25. 
- Replace all elements less than 30 with 0. 
- Count the number of elements divisible by 5. 


In [110]:
n1 = np.random.randint(10, 50, 15 )
print(n1)
print("-"*40)


greaterThan25 = n1[n1 > 25]
print(greaterThan25)
print("-"*40)


n1[n1 < 30] = 0
print(n1)
print("-"*40)

div_by_5 = n1[n1 % 5 == 0]
count = len(div_by_5)
print(count)


[40 43 35 23 49 14 33 48 49 41 29 43 43 44 19]
----------------------------------------
[40 43 35 49 33 48 49 41 29 43 43 44]
----------------------------------------
[40 43 35  0 49  0 33 48 49 41  0 43 43 44  0]
----------------------------------------
6


### Task 6: Working with Built-in Functions 
#### 1. Use NumPy's built-in functions to:  
- Create an array of 10 equally spaced values between 0 and 1. 
- Create an identity matrix of size 4x4. 
- Generate a 1D array of 20 random integers between 1 and 100, 
sort it, and find the 5 largest elements. 


In [111]:
arr = np.linspace(0,1,10)
print(arr)
print('-'*35)

print('Identity Matrix')
print('-'*35)
print(np.eye(4, dtype=int))

print('-'*35)

OneD = np.random.randint(1, 100, 20)
print("Original Array : ",OneD)
print('-'*35)
sortArr = np.sort(OneD)
print("Sorted Array : ",sortArr)
print('-'*35)

print("Largest 5 element in array : ",sortArr[-5:])
print('-'*35)




[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
-----------------------------------
Identity Matrix
-----------------------------------
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
-----------------------------------
Original Array :  [22 46 28 66 72 10 95 67 90 63 58 82 40 91 21 37 71 97 84 98]
-----------------------------------
Sorted Array :  [10 21 22 28 37 40 46 58 63 66 67 71 72 82 84 90 91 95 97 98]
-----------------------------------
Largest 5 element in array :  [90 91 95 97 98]
-----------------------------------




### Task 7: Generic 
#### 1. Create a Python program that:  
- Generates two large random arrays of size (100, 100). 
- Performs matrix multiplication on the two arrays. 
- Finds the determinant and inverse of the resulting matrix (if 
possible). 
- Measures the time taken to complete these operations. 


In [112]:
import numpy as np
import time

A = np.random.rand(100, 100)
B = np.random.rand(100, 100)

start = time.time()

C = np.dot(A, B)
det = np.linalg.det(C)

if not np.isclose(det, 0):
    inv = np.linalg.inv(C)
    print("Inverse Matrix:\n", inv)
else:
    print("Matrix is not invertible")
print('-'*35)
end = time.time()
print("Determinant:", det)
print('-'*35)
print("Time taken:", end - start, "seconds")
print('-'*35)


Inverse Matrix:
 [[ 1.05596753  0.24562181  0.95699672 ... -0.43475059  0.77041635
   0.0257486 ]
 [ 0.26455379  0.03339718  0.88808182 ...  0.46322062  0.43522243
   1.08749055]
 [ 0.46644362 -0.09676565 -0.63900311 ... -1.10598019 -0.19747398
  -2.26525412]
 ...
 [ 0.97047961 -0.01162692  0.70809621 ...  0.21472186  0.84627522
   0.04439616]
 [ 1.08485581 -0.57510067  0.27793142 ... -0.4221841   0.62166469
   0.00967826]
 [-0.27052213  0.97688767  0.732653   ... -0.68745861 -0.50857554
   0.36098054]]
-----------------------------------
Determinant: 5.0906571912412635e+51
-----------------------------------
Time taken: 0.13565778732299805 seconds
-----------------------------------
